/**
 * Map helpers for the TripSync map view.
 *
 * These utilities transform itinerary Activity_Blocks into map-ready data:
 *  - convert blocks (which may lack coordinates) into typed pins,
 *  - group pins by day,
 *  - assign a distinct, stable color per day, and
 *  - build chronological route segments within each day.
 *
 * They are intentionally pure and framework-free so they can be unit-tested
 * without a DOM or Leaflet.
 */

import type { ActivityCategory } from '@tripsync/shared';

/** A single map marker derived from an Activity_Block with valid coordinates. */
export interface MapPin {
  blockId: string;
  latitude: number;
  longitude: number;
  title: string;
  category: ActivityCategory;
  dayNumber: number;
  /** Start time as "HH:mm" (24h), or null when unscheduled. */
  startTime: string | null;
  /** End time as "HH:mm" (24h), or null when open-ended. */
  endTime?: string | null;
}

/** A directed connection between two consecutive pins within the same day. */
export interface RouteSegment {
  from: MapPin;
  to: MapPin;
  /** Straight-line/route distance in meters. Null until enriched by routing. */
  distance: number | null;
  /** Travel duration in seconds. Null until enriched by routing. */
  duration: number | null;
}

/**
 * Minimal shape of an Activity_Block needed to build pins. Accepts the full
 * ActivityBlock as well as lighter client-side representations, as long as the
 * mapping fields are present.
 */
export interface BlockLike {
  id: string;
  title: string;
  category: ActivityCategory;
  latitude: number | null;
  longitude: number | null;
  startTime: string | null;
  endTime?: string | null;
  /** The day this block belongs to. */
  dayNumber: number;
}

/**
 * Curated palette of visually distinct, high-contrast colors used for the
 * first several days. Chosen to remain distinguishable on an OSM basemap.
 */
const DAY_COLOR_PALETTE: string[] = [
  '#c13a28', // terracotta (primary)
  '#b8912e', // mustard gold (secondary)
  '#b0744a', // terracotta brown (travel)
  '#1e9e72', // teal green (success)
  '#4c463c', // warm charcoal (stay)
  '#7c5cbf', // muted violet
  '#2f7fae', // dusty blue
  '#c2557a', // dusty rose
  '#6b8e23', // olive
  '#9a6324', // brown
];

/**
 * Converts an HSL color to a #rrggbb hex string.
 * h in [0,360), s and l in [0,1].
 */
function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = h / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r = 0;
  let g = 0;
  let b = 0;
  if (hp >= 0 && hp < 1) [r, g, b] = [c, x, 0];
  else if (hp < 2) [r, g, b] = [x, c, 0];
  else if (hp < 3) [r, g, b] = [0, c, x];
  else if (hp < 4) [r, g, b] = [0, x, c];
  else if (hp < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const m = l - c / 2;
  const toHex = (v: number) =>
    Math.round((v + m) * 255)
      .toString(16)
      .padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

/**
 * Assigns a distinct color to each day number from 1..totalDays.
 *
 * The first {@link DAY_COLOR_PALETTE} days use hand-picked colors; beyond that
 * colors are generated by evenly spacing hues around the wheel so every day
 * still receives a unique, deterministic color.
 *
 * @param totalDays number of days in the trip (values <= 0 yield an empty map)
 * @returns Map keyed by dayNumber (1-based) -> "#rrggbb" hex color
 */
export function assignDayColors(totalDays: number): Map<number, string> {
  const colors = new Map<number, string>();
  if (!Number.isFinite(totalDays) || totalDays <= 0) return colors;

  const count = Math.floor(totalDays);
  for (let day = 1; day <= count; day++) {
    if (day <= DAY_COLOR_PALETTE.length) {
      colors.set(day, DAY_COLOR_PALETTE[day - 1]);
    } else {
      // Spread remaining hues evenly to keep them distinct from one another.
      const overflowIndex = day - DAY_COLOR_PALETTE.length - 1;
      const overflowTotal = Math.max(1, count - DAY_COLOR_PALETTE.length);
      const hue = Math.round((overflowIndex / overflowTotal) * 360);
      colors.set(day, hslToHex(hue, 0.65, 0.5));
    }
  }
  return colors;
}

/**
 * Returns true only for a finite latitude/longitude pair that falls inside the
 * valid geographic range (lat ∈ [-90, 90], lng ∈ [-180, 180]).
 *
 * Guards the map against nulls, NaN/Infinity, and out-of-range coordinates that
 * could otherwise place a marker in a nonsensical spot or make Leaflet throw.
 */
export function isValidCoordinate(latitude: number | null, longitude: number | null): boolean {
  if (latitude == null || longitude == null) return false;
  if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) return false;
  if (latitude < -90 || latitude > 90) return false;
  if (longitude < -180 || longitude > 180) return false;
  return true;
}

/**
 * Converts Activity_Blocks into map pins, keeping only those with a valid
 * latitude/longitude pair. Blocks missing a coordinate, or carrying a NaN,
 * infinite, or out-of-range value, are dropped so no pin is rendered for them.
 */
export function toMapPins(blocks: BlockLike[]): MapPin[] {
  const pins: MapPin[] = [];
  for (const block of blocks) {
    const { latitude, longitude } = block;
    if (!isValidCoordinate(latitude, longitude)) {
      continue;
    }
    // `isValidCoordinate` guarantees both are finite, in-range numbers.
    pins.push({
      blockId: block.id,
      latitude: latitude as number,
      longitude: longitude as number,
      title: block.title,
      category: block.category,
      dayNumber: block.dayNumber,
      startTime: block.startTime,
      endTime: block.endTime ?? null,
    });
  }
  return pins;
}

/**
 * Groups pins by their day number.
 *
 * The returned map is ordered by ascending day number, and within each day the
 * pins are ordered chronologically by {@link comparePinsByTime}.
 */
export function groupPinsByDay(pins: MapPin[]): Map<number, MapPin[]> {
  const grouped = new Map<number, MapPin[]>();
  for (const pin of pins) {
    const existing = grouped.get(pin.dayNumber);
    if (existing) existing.push(pin);
    else grouped.set(pin.dayNumber, [pin]);
  }

  // Sort each day's pins chronologically.
  for (const dayPins of grouped.values()) {
    dayPins.sort(comparePinsByTime);
  }

  // Return a map ordered by ascending day number.
  return new Map([...grouped.entries()].sort((a, b) => a[0] - b[0]));
}

/**
 * Parses an "HH:mm" time string into minutes since midnight.
 * Returns null for null/empty/malformed input.
 */
function timeToMinutes(time: string | null): number | null {
  if (!time) return null;
  const match = /^(\d{1,2}):(\d{2})$/.exec(time.trim());
  if (!match) return null;
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  if (hours > 23 || minutes > 59) return null;
  return hours * 60 + minutes;
}

/**
 * Orders two pins chronologically by start time. Pins without a start time are
 * placed after timed pins; ties fall back to a stable title/blockId compare.
 */
function comparePinsByTime(a: MapPin, b: MapPin): number {
  const ta = timeToMinutes(a.startTime);
  const tb = timeToMinutes(b.startTime);
  if (ta != null && tb != null && ta !== tb) return ta - tb;
  if (ta != null && tb == null) return -1;
  if (ta == null && tb != null) return 1;
  // Deterministic tiebreaker so ordering is stable across runs.
  return a.blockId.localeCompare(b.blockId);
}

/**
 * Builds route segments connecting consecutive pins within each day in
 * chronological (start-time) order.
 *
 * Pins are grouped by day; within a day the pins are ordered by start time and
 * a segment is emitted between each adjacent pair. Days with fewer than two
 * pins contribute no segments. Distance and duration are left null for a later
 * routing step to populate.
 */
export function buildRouteSegments(pins: MapPin[]): RouteSegment[] {
  const segments: RouteSegment[] = [];
  const byDay = groupPinsByDay(pins);

  for (const dayPins of byDay.values()) {
    for (let i = 0; i < dayPins.length - 1; i++) {
      segments.push({
        from: dayPins[i],
        to: dayPins[i + 1],
        distance: null,
        duration: null,
      });
    }
  }
  return segments;
}

/** Mean earth radius in meters, used by the haversine distance estimate. */
const EARTH_RADIUS_M = 6_371_008.8;

/**
 * Average travel speed (m/s) used to turn a straight-line distance into a rough
 * duration estimate. ~20 km/h approximates mixed walking/city transit and keeps
 * the estimate conservative until a real routing API is wired in.
 */
const ESTIMATED_SPEED_MPS = 20_000 / 3600;

const toRadians = (deg: number): number => (deg * Math.PI) / 180;

/** Any object carrying a latitude/longitude pair. */
export interface LatLngLike {
  latitude: number;
  longitude: number;
}

/**
 * Great-circle ("as the crow flies") distance between two coordinates in
 * meters, via the haversine formula. This is a straight-line estimate — it
 * ignores roads, terrain and one-way streets.
 */
export function haversineDistanceMeters(from: LatLngLike, to: LatLngLike): number {
  const lat1 = toRadians(from.latitude);
  const lat2 = toRadians(to.latitude);
  const dLat = lat2 - lat1;
  const dLng = toRadians(to.longitude - from.longitude);

  const sinLat = Math.sin(dLat / 2);
  const sinLng = Math.sin(dLng / 2);
  const a = sinLat * sinLat + Math.cos(lat1) * Math.cos(lat2) * sinLng * sinLng;
  // clamp guards against tiny FP overshoot before asin/sqrt
  const c = 2 * Math.asin(Math.min(1, Math.sqrt(a)));
  return EARTH_RADIUS_M * c;
}

/**
 * Fills in straight-line distance (and a rough duration) on route segments that
 * don't have them yet. Segments already enriched by a routing API are returned
 * untouched, so this can safely run over mixed data.
 */
export function withEstimatedDistances(segments: RouteSegment[]): RouteSegment[] {
  return segments.map((segment) => {
    if (segment.distance != null) return segment;
    const distance = haversineDistanceMeters(segment.from, segment.to);
    return {
      ...segment,
      distance,
      duration: segment.duration ?? Math.round(distance / ESTIMATED_SPEED_MPS),
    };
  });
}

/**
 * Formats a distance in meters for display: "450 m", "1.2 km", "18 km".
 */
export function formatDistance(meters: number | null): string {
  if (meters == null || !Number.isFinite(meters)) return '';
  if (meters < 1000) return `${Math.round(meters)} m`;
  const km = meters / 1000;
  return `${km < 10 ? km.toFixed(1) : Math.round(km)} km`;
}

/**
 * Formats a duration in seconds for display: "8 min", "1 h 20 min".
 */
export function formatDuration(seconds: number | null): string {
  if (seconds == null || !Number.isFinite(seconds)) return '';
  const totalMinutes = Math.max(1, Math.round(seconds / 60));
  if (totalMinutes < 60) return `${totalMinutes} min`;
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return minutes === 0 ? `${hours} h` : `${hours} h ${minutes} min`;
}

/** Bounding box as [[southLat, westLng], [northLat, eastLng]]. */
export type LatLngBoundsTuple = [[number, number], [number, number]];

/**
 * Computes the bounding box enclosing all pins, for auto-fitting the map view.
 * Returns null when there are no pins. A single pin yields a degenerate box —
 * callers should pair `fitBounds` with a max zoom.
 */
export function computePinsBounds(pins: MapPin[]): LatLngBoundsTuple | null {
  if (pins.length === 0) return null;
  let south = pins[0].latitude;
  let north = pins[0].latitude;
  let west = pins[0].longitude;
  let east = pins[0].longitude;
  for (const pin of pins) {
    if (pin.latitude < south) south = pin.latitude;
    if (pin.latitude > north) north = pin.latitude;
    if (pin.longitude < west) west = pin.longitude;
    if (pin.longitude > east) east = pin.longitude;
  }
  return [
    [south, west],
    [north, east],
  ];
}

/**
 * Computes a reasonable [lat, lng] center for a set of pins by averaging their
 * coordinates. Returns null when there are no pins (caller should fall back to
 * a geocoded destination or a sensible default).
 */
export function computePinsCenter(pins: MapPin[]): [number, number] | null {
  if (pins.length === 0) return null;
  let latSum = 0;
  let lngSum = 0;
  for (const pin of pins) {
    latSum += pin.latitude;
    lngSum += pin.longitude;
  }
  return [latSum / pins.length, lngSum / pins.length];
}
